package com.iodesystems.ts.lib

import com.iodesystems.ts.Emitter.Output
import java.io.File
import kotlin.test.assertTrue

// Concatenate all emitted TypeScript (lib, types, apis) to a single string
fun Output.ts(): String = files.joinToString("\n") { it.content.toString() }

// Concatenate only API files (exclude lib and shared types) to a single string
fun Output.tsApis(): String = files
    .filter { f ->
        val name = f.file.name
        name != "api-lib.ts" && name != "api-types.ts"
    }
    .sortedBy { it.file.name }
    .joinToString("\n") { it.content.toString() }


fun getExternalClasspath(): List<String> {
    // Read the classpath from the file generated by test-project:test-core:writeClasspath
    // Tests run from core/ directory, so go up one level to find test-project
    val projectRoot = File("..").canonicalFile
    val classpathFile = File(projectRoot, "test-project/test-core/build/classpath.txt")

    assertTrue(classpathFile.exists(), "classpath.txt should exist at ${classpathFile.absolutePath}")

    return classpathFile.readLines().filter { it.isNotBlank() }
}